trigger: none

jobs:

  - job: MacOS
    strategy:
      matrix:
        catalina-std:
          image: macOS-10.15
          platform: x86-64
          version: 10.15
          buildType: "standard"
          prefix: "synergy"
    pool:
      vmImage: $[ variables['image'] ]

    #As apparently the trigger set to none doesn't work
    condition: eq(variables['Build.Reason'], 'Manual')

    variables:
      QT_VERSION: '5.15.2'
      Qt5_DIR: '/usr/local/opt/qt/5.15.2/clang_64'
      QT_PATH: '/usr/local/opt/qt/5.15.2/clang_64/bin'

    steps:
      - template: CI/checkout.yml
      - template: CI/MacOS/mac-build.yml